SELECT
       DISTINCT ID
     , EMAIL
     , FIRST_NAME
     , LAST_NAME
  FROM DEVELOPERS
  WHERE SUBSTRING(REVERSE(CONV(SKILL_CODE, 10, 2)), 9, 1) = '1'
     OR SUBSTRING(REVERSE(CONV(SKILL_CODE, 10, 2)), 11, 1) = '1'
  ORDER BY ID;